### ISSUE TITLE
No such file or directory - tpu civis (Errno:ENOENT)

### ISSUE THREAD

**Issue by hazelmeow** [arlimus/inquirer.rb#21]
C:/Ruby23/lib/ruby/gems/2.3.0/gems/inquirer-0.2.1/lib/inquirer/utils/iohelper.rb:109:in ``': No such file or directory - tput civis (Errno::ENOENT)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/inquirer-0.2.1/lib/inquirer/utils/iohelper.rb:109:in `without_cursor'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/inquirer-0.2.1/lib/inquirer/prompts/list.rb:95:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/inquirer-0.2.1/lib/inquirer/prompts/list.rb:120:in `ask'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/inquirer-0.2.1/lib/inquirer.rb:12:in `list'

**Comment by Punknoodles** [comment]
This happened when using Ask.list

**Comment by Punknoodles** [comment]
After a bit of digging: I was on Windows, and `tput` is a Unix command. Any way to add Windows support?
